# Generated by Django 4.2.7 on 2023-11-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaicommand',
            name='version',
            field=models.CharField(default='hi', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='openaicommand',
            name='category',
            field=models.CharField(blank=True, choices=[('Code Review', 'Code Review'), ('Automate', 'Automate'), ('Tester', 'Tester')], max_length=20, null=True),
        ),
    ]
