# Generated by Django 4.2.7 on 2023-11-17 15:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_openaicommand_version_alter_openaicommand_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaicommand',
            name='prompt',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='openaicommand',
            name='response',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
