# Generated by Django 4.2.7 on 2023-11-19 05:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_openaicommand_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaicommand',
            name='response',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
